/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medhealth.Views;

import medhealth.Connection.DatabaseConnection;
import medhealth.MedHealth;
import medhealth.Obat;
import medhealth.Pasien;
import java.awt.Color;
import java.sql.Statement;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author ASUS X455L
 */
public class v_home extends javax.swing.JFrame {
    Connection koneksi;
    /**
     * Creates new form v_home
     */
    public v_home() {
        initComponents();
        koneksi = DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_medhealt");
        showData();
        showStok();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPertama = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        DataPasien = new javax.swing.JPanel();
        DtPasien = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        StokObat = new javax.swing.JPanel();
        stkObat = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DataPane = new javax.swing.JPanel();
        DataSiswa2 = new javax.swing.JPanel();
        Head3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ScrollDatsis = new javax.swing.JScrollPane();
        TabelPasien = new javax.swing.JTable();
        Exit = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        DataObat1 = new javax.swing.JPanel();
        Head4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ScrollDaobat = new javax.swing.JScrollPane();
        TabelObat = new javax.swing.JTable();
        Exit1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnRefreshObat = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        btnTambah1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        PanelPertama.setBackground(new java.awt.Color(255, 255, 255));
        PanelPertama.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelPertamaMouseDragged(evt);
            }
        });
        PanelPertama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelPertamaMousePressed(evt);
            }
        });

        MenuPanel.setBackground(new java.awt.Color(0, 153, 153));

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medhealth/Images/logos.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        DataPasien.setBackground(new java.awt.Color(0, 153, 102));
        DataPasien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DataPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DataPasienMousePressed(evt);
            }
        });

        DtPasien.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        DtPasien.setForeground(new java.awt.Color(255, 255, 255));
        DtPasien.setText("DATA PASIEN");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medhealth/Images/Datasiswa2.png"))); // NOI18N

        javax.swing.GroupLayout DataPasienLayout = new javax.swing.GroupLayout(DataPasien);
        DataPasien.setLayout(DataPasienLayout);
        DataPasienLayout.setHorizontalGroup(
            DataPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataPasienLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DtPasien)
                .addContainerGap())
        );
        DataPasienLayout.setVerticalGroup(
            DataPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataPasienLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(DataPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DtPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StokObat.setBackground(new java.awt.Color(0, 153, 102));
        StokObat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StokObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StokObatMousePressed(evt);
            }
        });

        stkObat.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        stkObat.setForeground(new java.awt.Color(255, 255, 255));
        stkObat.setText("STOK OBAT");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medhealth/Images/Obat.png"))); // NOI18N

        javax.swing.GroupLayout StokObatLayout = new javax.swing.GroupLayout(StokObat);
        StokObat.setLayout(StokObatLayout);
        StokObatLayout.setHorizontalGroup(
            StokObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StokObatLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stkObat)
                .addContainerGap())
        );
        StokObatLayout.setVerticalGroup(
            StokObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StokObatLayout.createSequentialGroup()
                .addGroup(StokObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stkObat)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DataPasien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StokObat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(LOGO)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(LOGO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(DataPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StokObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DataPane.setBackground(new java.awt.Color(255, 255, 255));
        DataPane.setLayout(new java.awt.CardLayout());

        DataSiswa2.setBackground(new java.awt.Color(255, 255, 255));

        Head3.setBackground(new java.awt.Color(0, 153, 102));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("UKS/Data Pasien");

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tampilan Data Pasien UKS");

        javax.swing.GroupLayout Head3Layout = new javax.swing.GroupLayout(Head3);
        Head3.setLayout(Head3Layout);
        Head3Layout.setHorizontalGroup(
            Head3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Head3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Head3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Head3Layout.setVerticalGroup(
            Head3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Head3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        ScrollDatsis.setBackground(new java.awt.Color(255, 255, 255));
        ScrollDatsis.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ScrollDatsis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ScrollDatsis.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        TabelPasien.setAutoCreateRowSorter(true);
        TabelPasien.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        TabelPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelPasien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabelPasien.setGridColor(new java.awt.Color(255, 255, 255));
        TabelPasien.setRowHeight(24);
        TabelPasien.setSelectionBackground(new java.awt.Color(250, 51, 51));
        TabelPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPasienMouseClicked(evt);
            }
        });
        ScrollDatsis.setViewportView(TabelPasien);
        TabelPasien.getAccessibleContext().setAccessibleParent(ScrollDatsis);

        Exit.setBackground(new java.awt.Color(255, 255, 255));
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("X");

        javax.swing.GroupLayout ExitLayout = new javax.swing.GroupLayout(Exit);
        Exit.setLayout(ExitLayout);
        ExitLayout.setHorizontalGroup(
            ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitLayout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        ExitLayout.setVerticalGroup(
            ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        btnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        btnRefresh.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medhealth/Images/refresh.png"))); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.setBorder(null);
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRefreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRefreshMouseExited(evt);
            }
        });
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medhealth/Images/Edit.png"))); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.setBorder(null);
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(255, 255, 255));
        btnTambah.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medhealth/Images/TambahData.png"))); // NOI18N
        btnTambah.setText("ADD");
        btnTambah.setBorder(null);
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahMouseExited(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medhealth/Images/Eraser.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setBorder(null);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataSiswa2Layout = new javax.swing.GroupLayout(DataSiswa2);
        DataSiswa2.setLayout(DataSiswa2Layout);
        DataSiswa2Layout.setHorizontalGroup(
            DataSiswa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Head3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataSiswa2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DataSiswa2Layout.createSequentialGroup()
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
            .addComponent(ScrollDatsis)
        );
        DataSiswa2Layout.setVerticalGroup(
            DataSiswa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataSiswa2Layout.createSequentialGroup()
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Head3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(DataSiswa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(ScrollDatsis, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
        );

        ScrollDatsis.getAccessibleContext().setAccessibleDescription("");

        DataPane.add(DataSiswa2, "card2");

        DataObat1.setBackground(new java.awt.Color(255, 255, 255));

        Head4.setBackground(new java.awt.Color(94, 77, 255));
        Head4.setPreferredSize(new java.awt.Dimension(718, 109));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("UKS/Data Obat");

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Stok obat yang tersedia di UKS");

        javax.swing.GroupLayout Head4Layout = new javax.swing.GroupLayout(Head4);
        Head4.setLayout(Head4Layout);
        Head4Layout.setHorizontalGroup(
            Head4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Head4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Head4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addContainerGap(403, Short.MAX_VALUE))
        );
        Head4Layout.setVerticalGroup(
            Head4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Head4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        ScrollDaobat.setBackground(new java.awt.Color(255, 255, 255));
        ScrollDaobat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ScrollDaobat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ScrollDaobat.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        TabelObat.setAutoCreateRowSorter(true);
        TabelObat.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        TabelObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelObat.setGridColor(new java.awt.Color(255, 255, 255));
        TabelObat.setRowHeight(24);
        TabelObat.setRowSorter(null);
        TabelObat.setSelectionBackground(new java.awt.Color(255, 25, 106));
        TabelObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelObatMouseClicked(evt);
            }
        });
        ScrollDaobat.setViewportView(TabelObat);

        Exit1.setBackground(new java.awt.Color(255, 255, 255));
        Exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Exit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Exit1MousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setText("X");

        javax.swing.GroupLayout Exit1Layout = new javax.swing.GroupLayout(Exit1);
        Exit1.setLayout(Exit1Layout);
        Exit1Layout.setHorizontalGroup(
            Exit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(Exit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Exit1Layout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        Exit1Layout.setVerticalGroup(
            Exit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Exit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Exit1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        btnRefreshObat.setBackground(new java.awt.Color(255, 255, 255));
        btnRefreshObat.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        btnRefreshObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medhealth/Images/refresh.png"))); // NOI18N
        btnRefreshObat.setText("REFRESH");
        btnRefreshObat.setBorder(null);
        btnRefreshObat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefreshObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRefreshObatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRefreshObatMouseExited(evt);
            }
        });
        btnRefreshObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshObatActionPerformed(evt);
            }
        });

        btnEdit1.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnEdit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medhealth/Images/EditObat.png"))); // NOI18N
        btnEdit1.setText("EDIT");
        btnEdit1.setBorder(null);
        btnEdit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEdit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEdit1MouseExited(evt);
            }
        });
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        btnTambah1.setBackground(new java.awt.Color(255, 255, 255));
        btnTambah1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        btnTambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medhealth/Images/StokData.png"))); // NOI18N
        btnTambah1.setText("ADD");
        btnTambah1.setBorder(null);
        btnTambah1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambah1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambah1MouseExited(evt);
            }
        });
        btnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah1ActionPerformed(evt);
            }
        });

        btnDelete1.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        btnDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medhealth/Images/Delete_1.png"))); // NOI18N
        btnDelete1.setText("DELETE");
        btnDelete1.setBorder(null);
        btnDelete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDelete1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDelete1MouseExited(evt);
            }
        });
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataObat1Layout = new javax.swing.GroupLayout(DataObat1);
        DataObat1.setLayout(DataObat1Layout);
        DataObat1Layout.setHorizontalGroup(
            DataObat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Head4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataObat1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Exit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(ScrollDaobat)
            .addGroup(DataObat1Layout.createSequentialGroup()
                .addComponent(btnRefreshObat, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DataObat1Layout.setVerticalGroup(
            DataObat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataObat1Layout.createSequentialGroup()
                .addComponent(Exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Head4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DataObat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshObat, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ScrollDaobat, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
        );

        DataPane.add(DataObat1, "card3");

        javax.swing.GroupLayout PanelPertamaLayout = new javax.swing.GroupLayout(PanelPertama);
        PanelPertama.setLayout(PanelPertamaLayout);
        PanelPertamaLayout.setHorizontalGroup(
            PanelPertamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPertamaLayout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DataPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPertamaLayout.setVerticalGroup(
            PanelPertamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DataPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPertama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPertama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    static int xx;
    static int xy;
    private void PanelPertamaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPertamaMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_PanelPertamaMouseDragged

    private void PanelPertamaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPertamaMousePressed
        // TODO add your handling code here:
         xx = evt.getX();
         xy = evt.getY();
    }//GEN-LAST:event_PanelPertamaMousePressed

    private void DataPasienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataPasienMousePressed
        // TODO add your handling code here:
        setSideColor(DataPasien);
        resetSideColor(StokObat);
        
        DataPane.removeAll();
        DataPane.repaint();
        DataPane.revalidate();
        
        DataPane.add(DataSiswa2);
        DataPane.repaint();
        DataPane.revalidate();
        showData();
    }//GEN-LAST:event_DataPasienMousePressed

    private void StokObatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StokObatMousePressed
        // TODO add your handling code here:
        setSideColor(StokObat);
        resetSideColor(DataPasien);
        
        DataPane.removeAll();
        DataPane.repaint();
        DataPane.revalidate();
        
        DataPane.add(DataObat1);
        DataPane.repaint();
        DataPane.revalidate();
        showStok();
    }//GEN-LAST:event_StokObatMousePressed
int baris;
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String delete = TabelPasien.getValueAt(baris, 1).toString();
        try{
            Statement stmt = koneksi.createStatement();
            String query = "DELETE FROM pasien WHERE id = '" + delete + "'";
            int berhasil = stmt.executeUpdate(query);
            if(berhasil == 1){
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                dtm.getDataVector().removeAllElements();
                showData();
                showStok();
            }else{
                JOptionPane.showMessageDialog(null, "Data gagal dihapus");
            }
        }catch(SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        // TODO add your handling code here:
        resetButtonColor(btnDelete);
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        // TODO add your handling code here:
        setButtonColor(btnDelete);
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try{
            Statement stmt = koneksi.createStatement();
            String teks = "Move Tambah Data";

            System.out.println(teks);
            v_ManageData tambahdata = new v_ManageData(this, true, "Tambah", "");
            tambahdata.setVisible(true);
            dispose();

            stmt.close();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseExited
        // TODO add your handling code here:
        resetButtonColor(btnTambah);
    }//GEN-LAST:event_btnTambahMouseExited

    private void btnTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseEntered
        // TODO add your handling code here:
        setButtonColor(btnTambah);
    }//GEN-LAST:event_btnTambahMouseEntered

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String ID = TabelPasien.getValueAt(baris, 1).toString();
        try{
            Statement stmt = koneksi.createStatement();
            String teks = "Move Edit Data";

            System.out.println(teks);
            v_ManageData tambahdata = new v_ManageData(this, true, "Edit", ID);
            tambahdata.setVisible(true);
            dispose();

            stmt.close();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
        // TODO add your handling code here:
        resetButtonColor(btnEdit);
    }//GEN-LAST:event_btnEditMouseExited

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        // TODO add your handling code here:
        setButtonColor(btnEdit);
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        showData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnRefreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseExited
        // TODO add your handling code here:
        resetButtonColor(btnRefresh);
    }//GEN-LAST:event_btnRefreshMouseExited

    private void btnRefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseEntered
        // TODO add your handling code here:
        setButtonColor(btnRefresh);
    }//GEN-LAST:event_btnRefreshMouseEntered

    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMousePressed

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        // TODO add your handling code here:
        resetColor(Exit);
    }//GEN-LAST:event_ExitMouseExited

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        setColor(Exit);
    }//GEN-LAST:event_ExitMouseEntered

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        String delete = TabelObat.getValueAt(baris, 1).toString();
        try{
            Statement stmt = koneksi.createStatement();
            String query = "DELETE FROM obat WHERE kd_obat = '" + delete + "'";
            int berhasil = stmt.executeUpdate(query);
            if(berhasil == 1){
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                dtm.getDataVector().removeAllElements();
                showStok();
                showData();
            }else{
                JOptionPane.showMessageDialog(null, "Data gagal dihapus");
            }
        }catch(SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnDelete1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelete1MouseExited
        // TODO add your handling code here:
        resetButtonColor(btnDelete1);
    }//GEN-LAST:event_btnDelete1MouseExited

    private void btnDelete1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelete1MouseEntered
        // TODO add your handling code here:
        setButtonColor(btnDelete1);
    }//GEN-LAST:event_btnDelete1MouseEntered

    private void btnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah1ActionPerformed
        // TODO add your handling code here:
        try{
            Statement stmt = koneksi.createStatement();
            String teks = "Move Tambah Data";

            System.out.println(teks);
            v_FormObat stok = new v_FormObat(this, true, "Tambah", "");
            stok.setVisible(true);
            dispose();

            stmt.close();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTambah1ActionPerformed

    private void btnTambah1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambah1MouseExited
        // TODO add your handling code here:
        resetButtonColor(btnTambah1);
    }//GEN-LAST:event_btnTambah1MouseExited

    private void btnTambah1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambah1MouseEntered
        // TODO add your handling code here:
        setButtonColor(btnTambah1);
    }//GEN-LAST:event_btnTambah1MouseEntered

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        // TODO add your handling code here:
        String kode = TabelObat.getValueAt(baris, 1).toString();
        try{
            Statement stmt = koneksi.createStatement();
            String teks = "Move Edit Data";

            System.out.println(teks);
            v_FormObat stok = new v_FormObat(this, true, "EditObat", kode);
            stok.setVisible(true);
            dispose();

            stmt.close();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnEdit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEdit1MouseExited
        // TODO add your handling code here:
        resetButtonColor(btnEdit1);
    }//GEN-LAST:event_btnEdit1MouseExited

    private void btnEdit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEdit1MouseEntered
        // TODO add your handling code here:
        setButtonColor(btnEdit1);
    }//GEN-LAST:event_btnEdit1MouseEntered

    private void btnRefreshObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshObatActionPerformed
        // TODO add your handling code here:
        showStok();
    }//GEN-LAST:event_btnRefreshObatActionPerformed

    private void btnRefreshObatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshObatMouseExited
        // TODO add your handling code here:
        resetButtonColor(btnRefreshObat);
    }//GEN-LAST:event_btnRefreshObatMouseExited

    private void btnRefreshObatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshObatMouseEntered
        // TODO add your handling code here:
        setButtonColor(btnRefreshObat);
    }//GEN-LAST:event_btnRefreshObatMouseEntered

    private void Exit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Exit1MousePressed

    private void Exit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit1MouseExited
        // TODO add your handling code here:
        resetColor(Exit1);
    }//GEN-LAST:event_Exit1MouseExited

    private void Exit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit1MouseEntered
        // TODO add your handling code here:
        setColor(Exit1);
    }//GEN-LAST:event_Exit1MouseEntered

    private void TabelObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelObatMouseClicked
        // TODO add your handling code here:
        baris = TabelObat.getSelectedRow();
    }//GEN-LAST:event_TabelObatMouseClicked

    private void TabelPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPasienMouseClicked
        // TODO add your handling code here:
        baris = TabelPasien.getSelectedRow();
    }//GEN-LAST:event_TabelPasienMouseClicked
    void setColor(JPanel panel){
        panel.setBackground(new Color(255, 0, 51));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(255, 255, 255));
    }
     void setSideColor(JPanel panel){
        panel.setBackground(new Color(60,149,243));
    }
    void resetSideColor(JPanel panel){
        panel.setBackground(new Color(51, 92, 160));
    }
    void setButtonColor(JButton button){
        button.setBackground(new Color(240, 240, 240));
    }
    void resetButtonColor(JButton button){
        button.setBackground(new Color(255, 255, 255));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the IDbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If IDbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_home().setVisible(true);
            }
        });
    }
    DefaultTableModel dtm;
    public void showData(){
        String[] kolom = {"No.", "ID", "Nama", "Ruangan", "Jengkel", "Ket. Sakit", "Tanggal", "email"};
        
        dtm = new DefaultTableModel(null, kolom);
        MedHealth.pasien = new Pasien();
        try{
            Statement stmt = koneksi.createStatement();
//            String query = "SELECT pasien.nis, pasien.nama, pasien.kelas, pasien.jenkel, pasien.ket_sakit, pasien.jenis_obat, obat.merk, petugas.username, pasien.tanggal FROM pasien "
//                    + "INNER JOIN obat ON (pasien.kd_obat = obat.kd_obat) INNER JOIN petugas ON (pasien.username = petugas.username)";
            
            String query = "SELECT * FROM pasien";
            ResultSet rs = stmt.executeQuery(query);
            int no = 1;
            while(rs.next()){
                MedHealth.pasien.setID(rs.getString("id"));
                MedHealth.pasien.setNama(rs.getString("nama"));
                MedHealth.pasien.setKelas(rs.getString("ruangan"));
                MedHealth.pasien.setJenkel(rs.getString("jengkel"));
                MedHealth.pasien.setKet_sakit(rs.getString("ket_sakit"));
                MedHealth.pasien.setTanggal(rs.getString("tanggal"));
                MedHealth.pasien.setEmail(rs.getString("email"));
                
                
                dtm.addRow(new String[] {no+"", MedHealth.pasien.getID(), MedHealth.pasien.getNama(),MedHealth.pasien.getKelas(),
                    MedHealth.pasien.getJenkel(),MedHealth.pasien.getKet_sakit(), MedHealth.pasien.getTanggal(), MedHealth.pasien.getEmail()});
                no++;
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        TabelPasien.setModel(dtm);
    }
    
    public void showStok(){
        String[] kolom = {"No.", "Kode Obat", "Merk", "Tanggal exp", "Jenis Obat", "Stok obat", "Ket. Obat"};
        
        dtm = new DefaultTableModel(null, kolom);
        MedHealth.obat = new Obat();
        try{
            Statement stmt = koneksi.createStatement();
            String query = "SELECT * FROM obat";
            ResultSet rs = stmt.executeQuery(query);
            int no = 1;
            while(rs.next()){
                MedHealth.obat.setKd_obat(rs.getString("kd_obat"));
                MedHealth.obat.setMerk(rs.getString("merk"));
                MedHealth.obat.setTanggal_kadaluarsa(rs.getString("tanggal_kadaluarsa")); 
                MedHealth.obat.setJenis_obat(rs.getString("jenis_obat"));
                MedHealth.obat.setStok_obat(rs.getString("stok_obat"));
                MedHealth.obat.setKet_obat(rs.getString("ket_obat")); 
                
                dtm.addRow(new String[] {no+"", MedHealth.obat.getKd_obat(), MedHealth.obat.getMerk(), MedHealth.obat.getTanggal_kadaluarsa(),
                    MedHealth.obat.getJenis_obat(), MedHealth.obat.getStok_obat(), MedHealth.obat.getKet_obat()});
                no++;
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        TabelObat.setModel(dtm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataObat1;
    private javax.swing.JPanel DataPane;
    private javax.swing.JPanel DataPasien;
    private javax.swing.JPanel DataSiswa2;
    private javax.swing.JLabel DtPasien;
    private javax.swing.JPanel Exit;
    private javax.swing.JPanel Exit1;
    private javax.swing.JPanel Head3;
    private javax.swing.JPanel Head4;
    private javax.swing.JLabel LOGO;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel PanelPertama;
    private javax.swing.JScrollPane ScrollDaobat;
    private javax.swing.JScrollPane ScrollDatsis;
    private javax.swing.JPanel StokObat;
    private javax.swing.JTable TabelObat;
    private javax.swing.JTable TabelPasien;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefreshObat;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambah1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel stkObat;
    // End of variables declaration//GEN-END:variables
}
